---
- name: Update GitHub Secret with IP from inventory
  hosts: localhost
  gather_facts: no
  vars:
    github_repo: "Kovalermag/diplom"  
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"  # Личный токен GitHub
  tasks:
    - name: Get IP address from inventory
      set_fact:
        server_ip: "{{ hostvars['webserver-instance']['ansible_host'] }}"

    - name: Get GitHub public key for secrets
      uri:
        url: "https://api.github.com/repos/{{ github_repo }}/actions/secrets/public-key"
        method: GET
        headers:
          Authorization: "Bearer {{ github_token }}"
          Accept: "application/vnd.github+json"
        return_content: yes
      register: public_key_response

    - name: Extract public key and key ID
      set_fact:
        public_key: "{{ public_key_response.json.key }}"
        key_id: "{{ public_key_response.json.key_id }}"

    - name: Encrypt the secret value
      set_fact:
        encrypted_value: "{{ server_ip | string | encrypt_secret(public_key) }}"

    - name: Update GitHub Secret
      uri:
        url: "https://api.github.com/repos/{{ github_repo }}/actions/secrets/SERVER_HOST"
        method: PUT
        headers:
          Authorization: "Bearer {{ github_token }}"
          Accept: "application/vnd.github+json"
        body:
          encrypted_value: "{{ encrypted_value }}"
          key_id: "{{ key_id }}"
        body_format: json